### ISSUE TITLE
aircraft control challenge, model turns left unexpectedly

### ISSUE THREAD

**Issue by sbowman-mitre** [mitre/FMACM#20]
This question came originally from @rtsleight. 
When having trouble with control behavior, how can low-level control calculations be recorded?

**Comment by sbowman-mitre** [comment]
The lateral control law is implemented in `AircraftControl::doLateralControl()`. At the end of that method there is a call to a singleton class `InternalObserver`. That call is a logging call to record cross-track error, track angle error, and bank angle commands. But, recording them in memory doesn't automatically mean they get dumped to the file system. To get the data on disk, you have to make one call at the end of the simulation to 'InternalObserver::process_cross()`; this will write out a CSV file that contains the data. I also recommend making one call prior to simulating: `InternalObserver::set_scenario_name(string in)`. This sets a string that will be used in the output file. So overall it's like this:

```c++
InternalObserver::set_scenario_name("control_test");

// Simulate until the end of time
for (...) {
    ++time;
}

// Generate output
InternalObserver::process_cross();

// exit simulation
```

Let me know if that doesn't work for you.

**Comment by rtsleight** [comment]
@sbowman-mitre I might have found a fix. It could be a windowsism. 

https://github.com/mitre/FMACM/blob/dce6c55823476df0cbad60b881de481f89f3b32f/AircraftDynamicsTestFramework/TestFrameworkAircraft.cpp#L177

current_guidance is declared as an output and used as an input. The version of current_guidance that gets sent to the function, m_precalc_traj.Update, with default values of a very large number instead of Units::ZERO_LENGTH. However, this causes the code to enter this if block:

https://github.com/mitre/FMACM/blob/dce6c55823476df0cbad60b881de481f89f3b32f/Public/AircraftControl.cpp#L164-L165

and set the e_xtrk (cross track error) to a very large number (because guidance.m_reference_bank_angle is a large number).

Declaring current_guidance in a line prior to using the variable fixed the issue for me:

`Guidance current_guidance; // RTS 8/20/2019: Bug fix in windows.`
`current_guidance = m_precalc_traj.Update(m_truth_state_vector_old, current_guidance);`

**Comment by sbowman-mitre** [comment]
Oh, super interesting. Thanks for reporting. Since we don't run on Windows, I've never seen this. But, it still sounds like something we can fix and is probably just sloppy initializing code on our part. I'll see what we can do to mitigate this in the future. Thanks!
