### ISSUE TITLE
Pressure calculation does not match BADA reference

### ISSUE THREAD

**Issue by rtsleight** [mitre/FMACM#25]
The BADA rev 3.13 calculation for pressure uses a different value for temperature at altitude compared to FMACM when using WeatherTruthByTime.

The call to convert TAS to CAS, https://github.com/mitre/FMACM/blob/e77471bc8af1c05faf6351bdedef75abae5d843a/Public/ThreeDOFDynamics.cpp#L119 
gets the temperature using 
https://github.com/mitre/FMACM/blob/e77471bc8af1c05faf6351bdedef75abae5d843a/Public/Atmosphere.cpp#L45
which is overriden in WeatherTruthByTime
https://github.com/mitre/FMACM/blob/e77471bc8af1c05faf6351bdedef75abae5d843a/AircraftDynamicsTestFramework/WeatherTruthByTime.cpp#L94
to get the "sensed temperature". 

As a result, temperature, T, used in 
https://github.com/mitre/FMACM/blob/e77471bc8af1c05faf6351bdedef75abae5d843a/Public/Atmosphere.cpp#L51
is the "sensed" temperature at altitude. Whereas, the BADA equation uses the standard (non-Delta T) temperature. BADA uses "sensed - Delta_T" or "T_< - Delta_T", where "T_< = T_0 + Delta_T + Beta_T,< * H_p,trop".

Crossing out the "Delta_T" value gives "T_0 + Beta_T,< * H_p,trop", which is the same as the standard atmosphere temperature.

**Should the "T" used above be replaced with the result of StandardAtmosphere::GetTemperature(...)?**

The rho equation also looks different than what is in BADA rev 3.13.

**Comment by sbowman-mitre** [comment]
Thanks for the clear issue statement & diagnosis. As you can see in the code comments, we use BADA 3.7 for all of our calculations. We are aware that later revisions of BADA updated the atmospheric model (among other things). We don't have any plans or possibility of updating to 3.13 right now. 

That said, this behavior isn't a bug. Or at least, I'm not convinced it is. We do intentionally allow the equations of motion to use the nowcast temperature as if it was the true environment that the aircraft is operating in. So, these truth atmospheric parameters inform state propagation. So, when ThreeDOFDynamics needs a mathematical calculation that is informed by atmospheric parameters (e.g. TAS2CAS), we query and use the environmental parameters.

So, that is all intentional. If your concern is that this is a mis-use of the BADA atmospheric model, I'm not sure I agree with you. The delta-T parameter is an allowable parameter in their 3.7 documentation & I feel we're using it correctly. But, let me do some review and get back to you.

In the meantime, we could also decide to not allow this override feature. I should look into that as a software possibility here.

**Comment by rtsleight** [comment]
Researching rev 3.7, it looks like the FMACM code does implement the equations in 3.7 correctly. BADA changed the atmosphere model in 3.8. 

The two pressure implementations give vastly different pressure values when dT=17K, rev 3.8+ pressure is 30% lower. Our simulation ran much better with the 3.8+ version, but was unable to overcome the ETA errors when using the 3.7 pressure values.

**Comment by sbowman-mitre** [comment]
Okay, so it sounds like you are saying that there's no bug here, but there is an indication that we should update FMACM to a more recent atmospheric model. I completely agree that an update is a goal (we've been moving the software design this direction intentionally b/c we knew this was coming), but we're not in a position to get the new software written right now. The rest of this conversation is less about the software and more about our research collaboration & approach. Let's discuss our options in our meeting tomorrow.

Do you mind if I close this?
